version: '3.4'

services:
  backend:
    image: ${DOCKER_REGISTRY-}example
    build:
      context: .
      dockerfile: Example/Dockerfile

  proxy:
   volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
   ports:
     - "80:80"  