version: '3.4'

services:
  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "5000:8080"
      - "5001:8081"
    depends_on:
      - postgres
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  # client:
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #     - WDS_SOCKET_PORT=0
  #   ports:
  #     - "5002:3000" 
    
  # proxy:
  #    volumes:
  #      - ./nginx.conf:/etc/nginx/nginx.conf
  #    ports:
  #      - "80:80"

  postgres:
     ports:
        - 5432:5432
     environment:
        - POSTGRES_DB=Users
        - POSTGRES_USER=Postgres
        - POSTGRES_PASSWORD=Postgres
     volumes:
        - ./.conteiners/products-db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
        - "5050:80"
    environment:
        PGADMIN_DEFAULT_EMAIL: Test@test.com
        PGADMIN_DEFAULT_PASSWORD: test
    
